In [1]:
import numpy as np

In [6]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape

(3, 5)

In [8]:
a.ndim

2

In [11]:
a.dtype.name

'int64'

In [13]:
#the size in bytes of each element of the array
a.itemsize 

8

In [15]:
a.size

15

In [14]:
type(a)

numpy.ndarray

In [18]:
b = np.array([6.6, 7, 8])
print(b)
print(type(b))
b.dtype

[6.6 7.  8. ]
<class 'numpy.ndarray'>


dtype('float64')

In [20]:
b = np.array([[1.65, 5, 10],(14, 34, 0.00)])
b

array([[ 1.65,  5.  , 10.  ],
       [14.  , 34.  ,  0.  ]])

In [22]:
c = np.array([[1, 3],[4, 5]], dtype=complex)
c

array([[1.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j]])

In [27]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones((2,4,6), dtype=np.int8)

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int8)

In [31]:
# function empty creates an array whose initial content is random and depends on the state of the memory
np.empty((3,2))

array([[3.9930686e-316, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000]])