In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
#the size in bytes of each element of the array
a.itemsize 

8

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6.6, 7, 8])
print(b)
print(type(b))
b.dtype

[6.6 7.  8. ]
<class 'numpy.ndarray'>


dtype('float64')

In [10]:
b = np.array([[1.65, 5, 10],(14, 34, 0.00)])
b

array([[ 1.65,  5.  , 10.  ],
       [14.  , 34.  ,  0.  ]])

In [11]:
c = np.array([[1, 3],[4, 5]], dtype=complex)
c

array([[1.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j]])

In [12]:
np.zeros_like(c)

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((2,4,6), dtype=np.int8)

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int8)

In [15]:
# function empty creates an array whose initial content is random and depends on the state of the memory
np.empty((3,2))

array([[2.980502e-316, 0.000000e+000],
       [0.000000e+000, 0.000000e+000],
       [0.000000e+000, 0.000000e+000]])

In [16]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [17]:
np.arange(0, 3, 0.4)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8])

In [18]:
# 9 numbers from 0 to 2
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
# useful to evaluate function at lots of points
from numpy import pi
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)

In [20]:
# Basic Operations
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

In [21]:
b**2

array([0, 1, 4, 9])

In [22]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [23]:
a < 35

array([ True,  True, False, False])

In [24]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
# Elementwise product
A * B

array([[2, 0],
       [0, 4]])

In [25]:
# Matrix product
A @ B

array([[5, 4],
       [3, 4]])

In [26]:
# or
A.dot(B)

array([[5, 4],
       [3, 4]])

In [27]:
rg = np.random.default_rng(1) # create instance of default random number generator
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
b += a
b
# a += b - Error!  b is not automatically converted to integer type

array([[1.51182162, 1.9504637 , 1.14415961],
       [1.94864945, 1.31183145, 1.42332645]])

In [28]:
# Universal functions
B = np.arange(3)
B

array([0, 1, 2])

In [29]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [30]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [31]:
C = np.array([2., -1, 4])
np.add(B,C)

array([2., 0., 6.])

In [32]:
# Indexing, Slicing and Iterating
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [33]:
a[2]

8

In [34]:
a[2:5]

array([ 8, 27, 64])

In [35]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [36]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [37]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [39]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [40]:
b[2,3]

23

In [41]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [42]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [43]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [44]:
b[-1]

array([40, 41, 42, 43])

In [45]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

In [46]:
c.shape

(2, 2, 3)

In [48]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [49]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [51]:
# Iterating is done with respect to first axis (rows)
for i in b:
    print(i)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [54]:
# Iterating through
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [55]:
# Shape manipulation
a = np.floor(10 * rg.random((3,4)))
a

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [56]:
a.shape

(3, 4)

In [57]:
# flattening
a.ravel()

array([8., 4., 5., 0., 7., 5., 3., 7., 3., 4., 1., 4.])

In [58]:
a.reshape(6,2)

array([[8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.],
       [3., 4.],
       [1., 4.]])

In [59]:
a.T

array([[8., 7., 3.],
       [4., 5., 4.],
       [5., 3., 1.],
       [0., 7., 4.]])

In [60]:
# resize = similar to inplace in pandas, modify array
a.resize((2,6))
a

array([[8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4.]])

In [63]:
# -1 means that dimension is automaticly calculated
a.reshape(3, -1)

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [64]:
# Stacking arrays
a = np.floor(10 * rg.random((2, 2)))
a

array([[2., 2.],
       [7., 2.]])

In [65]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[4., 9.],
       [9., 7.]])

In [66]:
np.vstack((a, b))

array([[2., 2.],
       [7., 2.],
       [4., 9.],
       [9., 7.]])

In [67]:
np.hstack((a, b))

array([[2., 2., 4., 9.],
       [7., 2., 9., 7.]])

In [68]:
np.column_stack((a, b))

array([[2., 2., 4., 9.],
       [7., 2., 9., 7.]])

In [69]:
a = np.array([4., 2.])
b = np.array([3., 8.])

In [71]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [72]:
np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [74]:
from numpy import newaxis
a[:, newaxis]  # view `a` as a 2D column vector

array([[4.],
       [2.]])

In [75]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [76]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [77]:
np.column_stack is np.hstack

False

In [78]:
np.row_stack is np.vstack

True

In [79]:
# Splitting arrays
a = np.floor(10 * rg.random((2,12)))
a

array([[5., 2., 1., 9., 5., 1., 6., 7., 6., 9., 0., 5.],
       [4., 0., 6., 8., 5., 2., 8., 5., 5., 7., 1., 8.]])

In [80]:
# Split 'a' into 3
np.hsplit(a, 3)

[array([[5., 2., 1., 9.],
        [4., 0., 6., 8.]]), array([[5., 1., 6., 7.],
        [5., 2., 8., 5.]]), array([[6., 9., 0., 5.],
        [5., 7., 1., 8.]])]

In [81]:
# Split 'a' after the third and the fourth column
np.hsplit(a, (3,4))

[array([[5., 2., 1.],
        [4., 0., 6.]]), array([[9.],
        [8.]]), array([[5., 1., 6., 7., 6., 9., 0., 5.],
        [5., 2., 8., 5., 5., 7., 1., 8.]])]

In [84]:
# COPIES AND VIEWS


a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [85]:
def f(x):
    print(id(x))
id(a)

139914355957168

In [86]:
f(a)

139914355957168


In [87]:
f(b)

139914355957168


In [88]:
# Different array objects can share the same data. The view method creates a new array object that looks at the same data.
c = a.view()
c is a

False

In [89]:
c.base is a # c is a view of the data owned by a

True

In [92]:
c = c.reshape((2, 6))  # a's shape doesn't change
a.shape

(3, 4)

In [94]:
c[0,4] = 1234
a # a's data changes

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [95]:
s = a[:, 1:3]
s[:] = 10  # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [96]:
# DEEP COPY
d = a.copy()
d is a

False

In [97]:
d.base is a

False

In [98]:
d[0, 0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [99]:
del a  # the memory of ``a`` can be released.