In [1]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [2]:
train_labels = []
train_samples = []

In [3]:
for i in range(50):
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(1)

  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(0)

In [4]:
for i in range(1000):
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(0)

  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(1)

In [5]:
train_labels = np.array(train_labels)

In [6]:
train_samples = np.array(train_samples)

In [7]:
train_labels, train_samples = shuffle(train_labels, train_samples)

In [8]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [9]:
scaled_train_samples

array([[0.25287356],
       [0.90804598],
       [0.85057471],
       ...,
       [0.09195402],
       [0.87356322],
       [0.02298851]])

In [10]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [11]:
model = Sequential([
    Dense(units=16, input_shape=(1,), activation='relu'),
    Dense(units=32, activation='relu'),
    Dense(units=2, activation='softmax')                    
])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [14]:
model.fit(x=scaled_train_samples, y=train_labels, batch_size=10, epochs=30, shuffle=True, verbose=2)

Epoch 1/30
210/210 - 1s - loss: 0.6401 - accuracy: 0.5429 - 777ms/epoch - 4ms/step
Epoch 2/30
210/210 - 0s - loss: 0.6132 - accuracy: 0.6176 - 271ms/epoch - 1ms/step
Epoch 3/30
210/210 - 0s - loss: 0.5828 - accuracy: 0.6900 - 255ms/epoch - 1ms/step
Epoch 4/30
210/210 - 0s - loss: 0.5521 - accuracy: 0.7371 - 237ms/epoch - 1ms/step
Epoch 5/30
210/210 - 0s - loss: 0.5142 - accuracy: 0.7843 - 239ms/epoch - 1ms/step
Epoch 6/30
210/210 - 0s - loss: 0.4776 - accuracy: 0.8310 - 245ms/epoch - 1ms/step
Epoch 7/30
210/210 - 0s - loss: 0.4455 - accuracy: 0.8552 - 249ms/epoch - 1ms/step
Epoch 8/30
210/210 - 0s - loss: 0.4168 - accuracy: 0.8695 - 239ms/epoch - 1ms/step
Epoch 9/30
210/210 - 0s - loss: 0.3921 - accuracy: 0.8810 - 409ms/epoch - 2ms/step
Epoch 10/30
210/210 - 0s - loss: 0.3713 - accuracy: 0.8957 - 399ms/epoch - 2ms/step
Epoch 11/30
210/210 - 0s - loss: 0.3537 - accuracy: 0.9005 - 412ms/epoch - 2ms/step
Epoch 12/30
210/210 - 0s - loss: 0.3394 - accuracy: 0.9143 - 428ms/epoch - 2ms/step
E

In [12]:
# Including Validation

model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x=scaled_train_samples, y=train_labels, validation_split=0.1, batch_size=10, epochs=30, shuffle=True, verbose=2)

Epoch 1/30
189/189 - 1s - loss: 0.6272 - accuracy: 0.5296 - val_loss: 0.5970 - val_accuracy: 0.5857 - 746ms/epoch - 4ms/step
Epoch 2/30
189/189 - 0s - loss: 0.6099 - accuracy: 0.5926 - val_loss: 0.5779 - val_accuracy: 0.6619 - 264ms/epoch - 1ms/step
Epoch 3/30
189/189 - 0s - loss: 0.5897 - accuracy: 0.6545 - val_loss: 0.5566 - val_accuracy: 0.7048 - 274ms/epoch - 1ms/step
Epoch 4/30
189/189 - 0s - loss: 0.5663 - accuracy: 0.7138 - val_loss: 0.5312 - val_accuracy: 0.7810 - 250ms/epoch - 1ms/step
Epoch 5/30
189/189 - 0s - loss: 0.5401 - accuracy: 0.7624 - val_loss: 0.5040 - val_accuracy: 0.8286 - 253ms/epoch - 1ms/step
Epoch 6/30
189/189 - 0s - loss: 0.5112 - accuracy: 0.7937 - val_loss: 0.4738 - val_accuracy: 0.8619 - 265ms/epoch - 1ms/step
Epoch 7/30
189/189 - 0s - loss: 0.4808 - accuracy: 0.8302 - val_loss: 0.4434 - val_accuracy: 0.8714 - 251ms/epoch - 1ms/step
Epoch 8/30
189/189 - 0s - loss: 0.4513 - accuracy: 0.8439 - val_loss: 0.4152 - val_accuracy: 0.8905 - 251ms/epoch - 1ms/step


In [13]:
test_labels = []
test_samples = []

In [14]:
for i in range(10):
  random_younger = randint(13,64)
  test_samples.append(random_younger)
  test_labels.append(1)

  random_older = randint(65,100)
  test_samples.append(random_older)
  test_labels.append(0)

In [15]:
for i in range(200):
  random_younger = randint(13,64)
  test_samples.append(random_younger)
  test_labels.append(0)

  random_older = randint(65,100)
  test_samples.append(random_older)
  test_labels.append(1)

In [16]:
test_labels = np.array(test_labels)

In [17]:
test_samples = np.array(test_samples)

In [18]:
test_labels, test_samples = shuffle(test_labels, test_samples)

In [19]:
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

In [20]:
# Predict
predictions = model.predict(x=scaled_test_samples, batch_size=10, verbose=0)

In [21]:
# Probability of 0 vs prob of 1
for i in predictions:
    print(i)

[0.8221348  0.17786522]
[0.02801149 0.9719885 ]
[0.02413108 0.9758689 ]
[0.9571816  0.04281845]
[0.16162267 0.8383773 ]
[0.9571295  0.04287058]
[0.9515566  0.04844338]
[0.95765144 0.04234859]
[0.7735207  0.22647925]
[0.9577977  0.04220226]
[0.2069146 0.7930854]
[0.95646745 0.04353257]
[0.06734919 0.93265074]
[0.03766857 0.96233135]
[0.84319144 0.15680861]
[0.02413108 0.9758689 ]
[0.29116014 0.70883983]
[0.95574194 0.04425805]
[0.01927517 0.9807248 ]
[0.9577977  0.04220226]
[0.32333964 0.67666036]
[0.01927517 0.9807248 ]
[0.06734919 0.93265074]
[0.95323956 0.04676045]
[0.03766857 0.96233135]
[0.95375055 0.04624944]
[0.16162267 0.8383773 ]
[0.65093243 0.3490675 ]
[0.9545072  0.04549287]
[0.04693653 0.9530634 ]
[0.02077674 0.97922325]
[0.07762647 0.92237353]
[0.2069146 0.7930854]
[0.9545072  0.04549287]
[0.05428018 0.94571984]
[0.9571295  0.04287058]
[0.9534957  0.04650427]
[0.5422171  0.45778298]
[0.35728297 0.64271706]
[0.12468608 0.87531394]
[0.95772076 0.04227925]
[0.23284152 0.767158

In [22]:
rounded_predictions = np.argmax(predictions, axis=-1)

In [26]:
for i in rounded_predictions:
    print(i)

0
1
1
0
1
0
0
0
0
0
1
0
1
1
0
1
1
0
1
0
1
1
1
0
1
0
1
0
0
1
1
1
1
0
1
0
0
0
1
1
0
1
0
0
0
0
1
0
1
1
1
1
0
0
0
0
1
0
0
0
0
1
1
1
1
0
0
0
0
0
0
1
0
0
0
1
1
0
1
0
0
1
1
0
1
0
1
1
0
1
1
1
0
0
1
0
0
1
0
1
0
1
1
1
0
0
1
0
0
1
0
0
1
0
1
0
1
1
1
0
0
1
0
1
0
0
1
0
1
0
1
1
0
1
1
0
1
0
1
1
0
1
1
0
1
0
1
1
1
1
1
1
0
1
1
1
0
0
0
0
1
1
1
0
1
1
1
0
0
1
1
1
0
0
0
0
1
0
1
0
1
1
0
0
0
1
0
0
1
0
1
1
0
0
1
1
0
0
1
0
0
0
0
0
0
1
1
0
0
1
1
0
0
0
0
1
1
1
1
0
1
0
0
0
0
1
0
0
1
0
1
1
0
1
0
1
0
1
0
1
1
1
1
0
0
0
1
1
1
1
0
0
1
1
0
1
0
1
1
0
0
1
1
1
1
0
1
1
1
0
0
0
0
0
1
1
1
0
1
0
0
1
0
1
1
0
1
0
1
0
0
1
1
0
1
1
1
0
1
1
1
0
0
0
1
1
0
0
1
1
0
1
0
1
0
1
0
1
1
1
1
0
0
0
1
1
0
0
1
1
1
1
1
0
0
0
1
1
1
0
0
1
0
0
1
0
1
1
0
0
0
1
1
0
1
1
1
1
1
0
0
0
1
0
1
1
1
0
1
0
1
0
1
1
0
1
1
1
1
0
1
0
1
1
1
0
0
1
0
0
1
0
0
1
1
0
1
0
1
1
1
0
0
0
1
1
1
1
0
0
1
0
0
0
0
0
1
1
0
1


In [38]:
from sklearn.metrics import plot_confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [39]:
cm = confusion_matrix(y_true=test_labels, y_pred=rounded_predictions)

In [40]:
cm

array([[193,  17],
       [ 10, 200]])

In [42]:
#Saving model
import os.path
if os.path.isfile('medical_model.h5') is False:
    model.save('medical_model.h5')

In [44]:
from tensorflow.keras.models import load_model
new_model = load_model('medical_model.h5')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [45]:
new_model.get_weights()

[array([[ 0.0382774 ,  0.6369174 , -0.32200822,  0.69540393,  0.23338819,
          0.6337996 , -0.41416967,  0.51830655,  0.6222532 ,  0.32025528,
         -0.5565654 , -0.01837575,  0.34964833, -0.245585  ,  0.50417036,
          0.5842677 ]], dtype=float32),
 array([ 0.25790957,  0.02003322,  0.        , -0.14948334, -0.09500302,
        -0.18758164,  0.        , -0.14344078, -0.14246699, -0.12387158,
         0.        ,  0.        , -0.12884058,  0.        , -0.1589475 ,
        -0.1963696 ], dtype=float32),
 array([[ 1.72848120e-01, -2.82161891e-01, -2.23050565e-01,
         -3.03213686e-01, -1.43338054e-01,  1.36924282e-01,
          1.57174334e-01,  2.07945425e-02,  3.39042813e-01,
         -3.25363576e-02,  4.07351553e-01, -1.90050080e-01,
         -1.31702155e-01,  4.88682687e-01, -5.79127967e-02,
         -1.30852565e-01, -4.12790738e-02, -2.39648834e-01,
          1.54609665e-01, -3.27223480e-01,  2.81644434e-01,
          1.45686910e-01,  4.37695861e-01,  2.85341054e-01,
 

In [46]:
new_model.optimizer

In [48]:
# Save only architecture, not weights
json_string = model.to_json()

In [49]:
json_string

'{"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 1], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_input"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_r

In [50]:
from tensorflow.keras.models import model_from_json
model_architecture = model_from_json(json_string)
model_architecture.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [51]:
# Save only weights
import os.path
if os.path.isfile('weights.h5') is False:
    model.save_weights('weights.h5')

In [52]:
model2 = Sequential([
    Dense(units=16, input_shape=(1,), activation='relu'),
    Dense(units=32, activation='relu'),
    Dense(units=2, activation='softmax')
])

In [53]:
model2.load_weights('weights.h5')

In [54]:
model2.get_weights()

[array([[ 0.0382774 ,  0.6369174 , -0.32200822,  0.69540393,  0.23338819,
          0.6337996 , -0.41416967,  0.51830655,  0.6222532 ,  0.32025528,
         -0.5565654 , -0.01837575,  0.34964833, -0.245585  ,  0.50417036,
          0.5842677 ]], dtype=float32),
 array([ 0.25790957,  0.02003322,  0.        , -0.14948334, -0.09500302,
        -0.18758164,  0.        , -0.14344078, -0.14246699, -0.12387158,
         0.        ,  0.        , -0.12884058,  0.        , -0.1589475 ,
        -0.1963696 ], dtype=float32),
 array([[ 1.72848120e-01, -2.82161891e-01, -2.23050565e-01,
         -3.03213686e-01, -1.43338054e-01,  1.36924282e-01,
          1.57174334e-01,  2.07945425e-02,  3.39042813e-01,
         -3.25363576e-02,  4.07351553e-01, -1.90050080e-01,
         -1.31702155e-01,  4.88682687e-01, -5.79127967e-02,
         -1.30852565e-01, -4.12790738e-02, -2.39648834e-01,
          1.54609665e-01, -3.27223480e-01,  2.81644434e-01,
          1.45686910e-01,  4.37695861e-01,  2.85341054e-01,
 